### PR TITLE
Fix Leftover Artifacts at End of Error Off Animation

### PR DESCRIPTION
**Pull request by tylerbwong**
Fixes the issue explained in the comments of #1.

When changing from an error state to any other state, there would be two diagonal line artifacts leftover at the end of the error off animation. Specifically, the object animators for the two paths that make of the exclamation point would animate the paths to not be completely invisible.

Here you can see the error off animation before and after these changes:

Before                                 |  After
:-------------------------:|:-------------------------:
 before |  after

To be honest, I kind of tweaked the path until they were not visible in the sample app anymore. There was no actual calculation or specific path manipulation.

### CODE REVIEW

**Comment by mattprecious** [comment]
Heya. Sorry for the delay in getting to this. I was hesitant to diverge from AOSP and wanted to check for any changes upstream before merging this. Turns out they've made some changes and I don't see any leftover artifacts in the new assets/animations. I've pulled them in in #12.

Thanks for the PR!

**Comment by tylerbwong** [comment]
Awesome! Even better. Thanks! :tada:

**Comment by tylerbwong** [comment]
Hey @mattprecious! Any ETA on when a new version with the latest AOSP sync changes will land?

**Comment by mattprecious** [comment]
Will try to push this week.

**Comment by mattprecious** [comment]
Done.

**Pull request closed without merging**
